#############################################################################
# Makefile for building: audi
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ../audi/audi.pro
# Template: app
# Command: /home/kuba/Qt/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../audi/audi.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../audi -I. -I/usr/lib/x86_64-linux-gnu -I../../5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/kuba/Qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = audi1.0.0
DISTDIR = /home/kuba/Qt/Projekty/build-audi/.tmp/audi1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/home/kuba/Qt/Projekty/audi/../../../../../usr/lib/x86_64-linux-gnu/ -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_datasets -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_line_descriptor -lopencv_optflow -lopencv_video -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_rgbd -lopencv_viz -lopencv_surface_matching -lopencv_text -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../audi/main.cpp 
OBJECTS       = main.o
DIST          = ../../5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.7/gcc_64/mkspecs/common/unix.conf \
		../../5.7/gcc_64/mkspecs/common/linux.conf \
		../../5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.7/gcc_64/mkspecs/qconfig.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.7/gcc_64/mkspecs/features/default_post.prf \
		../../5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../5.7/gcc_64/mkspecs/features/yacc.prf \
		../../5.7/gcc_64/mkspecs/features/lex.prf \
		../audi/audi.pro  ../audi/main.cpp
QMAKE_TARGET  = audi
DESTDIR       = 
TARGET        = audi


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../audi/audi.pro ../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.7/gcc_64/mkspecs/common/unix.conf \
		../../5.7/gcc_64/mkspecs/common/linux.conf \
		../../5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.7/gcc_64/mkspecs/qconfig.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.7/gcc_64/mkspecs/features/default_post.prf \
		../../5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../5.7/gcc_64/mkspecs/features/yacc.prf \
		../../5.7/gcc_64/mkspecs/features/lex.prf \
		../audi/audi.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../audi/audi.pro
../../5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../5.7/gcc_64/mkspecs/common/unix.conf:
../../5.7/gcc_64/mkspecs/common/linux.conf:
../../5.7/gcc_64/mkspecs/common/sanitize.conf:
../../5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../5.7/gcc_64/mkspecs/common/g++-base.conf:
../../5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../5.7/gcc_64/mkspecs/qconfig.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../5.7/gcc_64/mkspecs/features/qt_config.prf:
../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../5.7/gcc_64/mkspecs/features/spec_post.prf:
../../5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../5.7/gcc_64/mkspecs/features/default_pre.prf:
../../5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../5.7/gcc_64/mkspecs/features/default_post.prf:
../../5.7/gcc_64/mkspecs/features/qml_debug.prf:
../../5.7/gcc_64/mkspecs/features/warn_on.prf:
../../5.7/gcc_64/mkspecs/features/file_copies.prf:
../../5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../5.7/gcc_64/mkspecs/features/exceptions.prf:
../../5.7/gcc_64/mkspecs/features/yacc.prf:
../../5.7/gcc_64/mkspecs/features/lex.prf:
../audi/audi.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../audi/audi.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: ../audi/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../audi/main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

